INFO: Fake rate file /afs/cern.ch/work/s/strembat/WZ/dataOutput/FakesRates/fakeRateFinal-TightLepsFrom3MediumLeptons.root not found. It will be created.

 *** Break *** segmentation violation
[?1034hmakeFakeRates output filename:  /afs/cern.ch/work/s/strembat/WZ/dataOutput/FakesRates/fakeRateAug2018-TightLepsFrom3MediumLeptons.root
Processing channel eee for dataset ttz
extra_inputs:  [<ROOT.ScaleFactor object ("electronTightIdSF") at 0x686b9b0>, <ROOT.ScaleFactor object ("electronGsfSF") at 0x65f0300>, <ROOT.ScaleFactor object ("muonIsoSF") at 0x39d3e20>, <ROOT.ScaleFactor object ("muonTightIdSF") at 0x6697390>, <ROOT.ScaleFactor object ("pileupSF") at 0x6570fb0>]
selector_name:  FakeRateSelector
calling processLocalFiles:
arg1(select):  <ROOT.FakeRateSelector object ("FakeRateSelector") at 0x62d1a60>
arg2(file_path):  /data/kelong/DibosonAnalysisData/3MediumLeptons/2018-04-27-ttz-WZxsec2016-3MediumLeptonsNoVeto-v1/*
arg3(chan):  eee
check before loop
check inside loop, filename:  /data/kelong/DibosonAnalysisData/3MediumLeptons/2018-04-27-ttz-WZxsec2016-3MediumLeptonsNoVeto-v1/skim-5a4949a78a7a011cad5a5c9b986d7d7b.root
after ROOT.tfile
after trfile.Get(eee/ntuple )
before tree.Process



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000000385a6ac89e in waitpid () from /lib64/libc.so.6
#1  0x000000385a63e4e9 in do_system () from /lib64/libc.so.6
#2  0x00007f7bfa60e588 in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#3  0x00007f7bfa610a3c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#4  <signal handler called>
#5  0x00007f7bf093853e in WZSelectorBase::Process(long long) () from /afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/lib/slc6_amd64_gcc630/libAnalysisWZAnalysis.so
#6  0x00007f7bf094fe7e in FakeRateSelector::Process(long long) () from /afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/lib/slc6_amd64_gcc630/libAnalysisWZAnalysis.so
#7  0x00007f7bf088a170 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libTreePlayer.so
#8  0x00007f7bf1ea00cb in ?? ()
#9  0x00007f7bf1ea0060 in ?? ()
#10 0x00007fffb79d7ad0 in ?? ()
#11 0x00007fffb79d76a0 in ?? ()
#12 0x00007f7bfaedc821 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f7bf093853e in WZSelectorBase::Process(long long) () from /afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/lib/slc6_amd64_gcc630/libAnalysisWZAnalysis.so
#6  0x00007f7bf094fe7e in FakeRateSelector::Process(long long) () from /afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/lib/slc6_amd64_gcc630/libAnalysisWZAnalysis.so
#7  0x00007f7bf088a170 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libTreePlayer.so
#8  0x00007f7bf1ea00cb in ?? ()
#9  0x00007f7bf1ea0060 in ?? ()
#10 0x00007fffb79d7ad0 in ?? ()
#11 0x00007fffb79d76a0 in ?? ()
#12 0x00007f7bfaedc821 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
===========================================================


Traceback (most recent call last):
  File "./Utilities/scripts/makeFakeRates.py", line 117, in <module>
    addSumweights=True)
  File "/afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/src/Analysis/VVAnalysis/Utilities/scripts/python/SelectorTools.py", line 32, in applySelector
    processLocalFiles(select, file_path, chan)
  File "/afs/cern.ch/work/s/strembat/WZ/CMSSW_9_4_8/src/Analysis/VVAnalysis/Utilities/scripts/python/SelectorTools.py", line 75, in processLocalFiles
    tree.Process(selector, "")
TypeError: none of the 2 overloaded methods succeeded. Full details:
  Long64_t TTree::Process(const char* filename, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    could not convert argument 1 (expected string or Unicode object, FakeRateSelector found)
  Long64_t TTree::Process(TSelector* selector, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000000385a6ac89e in waitpid () from /lib64/libc.so.6
#1  0x000000385a63e4e9 in do_system () from /lib64/libc.so.6
#2  0x00007f7bfa60e588 in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#3  0x00007f7bfa610a3c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#4  <signal handler called>
#5  0x00007f7bfa514de3 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#6  0x00007f7bfa86898b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#7  0x00007f7bfa866cfc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#8  0x00007f7bfa87e778 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#9  0x00007f7bfa479ad9 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#10 0x00007f7bfa47a69e in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#11 0x00007f7bfa47ad29 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#12 0x00007f7bfaedc821 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#13 0x00007f7bfaedf9cf in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#14 0x00007f7bfaf01222 in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#15 0x00007f7bfaf00c99 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#16 0x00007f7bfaeff4b3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#17 0x00007f7bfaee5c19 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#18 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bfafe61d0, arg=arg
entry=0x7f7bfb0f4050, kw=kw
entry=0x0) at Objects/abstract.c:2546
#19 0x00007f7bfb2624a0 in do_call (nk=<optimized out>, na=0, pp_stack=0x7fffb79d7cc0, func=<optimized out>) at Python/ceval.c:4568
#20 call_function (oparg=<optimized out>, pp_stack=0x7fffb79d7cc0) at Python/ceval.c:4373
#21 PyEval_EvalFrameEx (f=f
entry=0x6cb1db0, throwflag=throwflag
entry=0) at Python/ceval.c:2987
#22 0x00007f7bfb2669bc in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f7bfb0f4068, argcount=0, kws=kws
entry=0x7f7bfb0f4068, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#23 0x00007f7bfb1dd3cd in function_call (func=0x7f7bf12e08c0, arg=0x7f7bfb0f4050, kw=0x7f7bf12bee88) at Objects/funcobject.c:526
#24 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bf12e08c0, arg=arg
entry=0x7f7bfb0f4050, kw=kw
entry=0x7f7bf12bee88) at Objects/abstract.c:2546
#25 0x00007f7bfb260f4c in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, pp_stack=0x7fffb79d7f68, func=0x7f7bf12e08c0) at Python/ceval.c:4663
#26 PyEval_EvalFrameEx (f=f
entry=0x7f7bf1118bf0, throwflag=throwflag
entry=0) at Python/ceval.c:3026
#27 0x00007f7bfb2669bc in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f7bfb0f4068, argcount=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#28 0x00007f7bfb1dd2fc in function_call (func=0x7f7bf12e0320, arg=0x7f7bfb0f4050, kw=0x0) at Objects/funcobject.c:526
#29 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bf12e0320, arg=arg
entry=0x7f7bfb0f4050, kw=<optimized out>) at Objects/abstract.c:2546
#30 0x00007f7bfb25c607 in PyEval_CallObjectWithKeywords (func=func
entry=0x7f7bf12e0320, arg=0x7f7bfb0f4050, arg
entry=0x0, kw=kw
entry=0x0) at Python/ceval.c:4219
#31 0x00007f7bfb28c687 in call_sys_exitfunc () at Python/pythonrun.c:1750
#32 Py_Finalize () at Python/pythonrun.c:423
#33 0x00007f7bfb2a2b6c in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:665
#34 0x000000385a61ed20 in __libc_start_main () from /lib64/libc.so.6
#35 0x0000000000400651 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f7bfa514de3 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#6  0x00007f7bfa86898b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#7  0x00007f7bfa866cfc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#8  0x00007f7bfa87e778 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#9  0x00007f7bfa479ad9 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#10 0x00007f7bfa47a69e in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#11 0x00007f7bfa47ad29 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#12 0x00007f7bfaedc821 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#13 0x00007f7bfaedf9cf in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#14 0x00007f7bfaf01222 in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#15 0x00007f7bfaf00c99 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#16 0x00007f7bfaeff4b3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#17 0x00007f7bfaee5c19 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#18 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bfafe61d0, arg=arg
entry=0x7f7bfb0f4050, kw=kw
entry=0x0) at Objects/abstract.c:2546
#19 0x00007f7bfb2624a0 in do_call (nk=<optimized out>, na=0, pp_stack=0x7fffb79d7cc0, func=<optimized out>) at Python/ceval.c:4568
#20 call_function (oparg=<optimized out>, pp_stack=0x7fffb79d7cc0) at Python/ceval.c:4373
#21 PyEval_EvalFrameEx (f=f
entry=0x6cb1db0, throwflag=throwflag
entry=0) at Python/ceval.c:2987
#22 0x00007f7bfb2669bc in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f7bfb0f4068, argcount=0, kws=kws
entry=0x7f7bfb0f4068, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#23 0x00007f7bfb1dd3cd in function_call (func=0x7f7bf12e08c0, arg=0x7f7bfb0f4050, kw=0x7f7bf12bee88) at Objects/funcobject.c:526
#24 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bf12e08c0, arg=arg
entry=0x7f7bfb0f4050, kw=kw
entry=0x7f7bf12bee88) at Objects/abstract.c:2546
#25 0x00007f7bfb260f4c in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, pp_stack=0x7fffb79d7f68, func=0x7f7bf12e08c0) at Python/ceval.c:4663
#26 PyEval_EvalFrameEx (f=f
entry=0x7f7bf1118bf0, throwflag=throwflag
entry=0) at Python/ceval.c:3026
#27 0x00007f7bfb2669bc in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals
entry=0x0, args=args
entry=0x7f7bfb0f4068, argcount=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#28 0x00007f7bfb1dd2fc in function_call (func=0x7f7bf12e0320, arg=0x7f7bfb0f4050, kw=0x0) at Objects/funcobject.c:526
#29 0x00007f7bfb1ac953 in PyObject_Call (func=func
entry=0x7f7bf12e0320, arg=arg
entry=0x7f7bfb0f4050, kw=<optimized out>) at Objects/abstract.c:2546
#30 0x00007f7bfb25c607 in PyEval_CallObjectWithKeywords (func=func
entry=0x7f7bf12e0320, arg=0x7f7bfb0f4050, arg
entry=0x0, kw=kw
entry=0x0) at Python/ceval.c:4219
#31 0x00007f7bfb28c687 in call_sys_exitfunc () at Python/pythonrun.c:1750
#32 Py_Finalize () at Python/pythonrun.c:423
#33 0x00007f7bfb2a2b6c in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:665
#34 0x000000385a61ed20 in __libc_start_main () from /lib64/libc.so.6
#35 0x0000000000400651 in _start ()
===========================================================


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-fmblme/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/ROOT.py", line 669, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset
Error in sys.exitfunc:

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000000385a6ac89e in waitpid () from /lib64/libc.so.6
#1  0x000000385a63e4e9 in do_system () from /lib64/libc.so.6
#2  0x00007f7bfa60e588 in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#3  0x00007f7bfa610a3c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#4  <signal handler called>
#5  0x00007f7bfa514de3 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#6  0x00007f7bfa86898b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#7  0x00007f7bfa866cfc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#8  0x00007f7bfa87e778 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#9  0x00007f7bfa87ebe7 in TFile::~TFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#10 0x00007f7bfa87eef9 in TFile::~TFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#11 0x00007f7bfa5c04c1 in TClass::Destructor(void*, bool) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#12 0x00007f7bfaee8847 in PyROOT::op_dealloc_nofree(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#13 0x00007f7bfaee88b9 in PyROOT::(anonymous namespace)::op_dealloc(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#14 0x00007f7bfb213382 in subtype_dealloc (self=0x7f7bf10e7fb0) at Objects/typeobject.c:1030
#15 0x00007f7bfb1dc0b9 in frame_dealloc (f=0x686f960) at Objects/frameobject.c:460
#16 0x00007f7bfb294feb in tb_dealloc (tb=0x7f7beff72c68) at Python/traceback.c:28
#17 0x00007f7bfb294ffb in tb_dealloc (tb=0x7f7beff72cf8) at Python/traceback.c:27
#18 0x00007f7bfb294ffb in tb_dealloc (tb=0x7f7beff72830) at Python/traceback.c:27
#19 0x00007f7bfb1f35e7 in insertdict_by_entry (value=0x7f7bfafdf4d0, ep=0x176d2a0, hash=5897959712516987849, key=0x7f7bfb0109d0, mp=0x7f7bfb12e280) at Objects/dictobject.c:519
#20 insertdict (mp=0x7f7bfb12e280, key=0x7f7bfb0109d0, hash=5897959712516987849, value=0x7f7bfafdf4d0) at Objects/dictobject.c:556
#21 0x00007f7bfb1f4fc7 in dict_set_item_by_hash_or_entry (ep=0x0, value=0x7f7bfafdf4d0, hash=<optimized out>, key=<optimized out>, op=0x7f7bfb12e280) at Objects/dictobject.c:765
#22 PyDict_SetItem (op=0x7f7bfb12e280, key=<optimized out>, value=0x7f7bfafdf4d0) at Objects/dictobject.c:818
#23 0x00007f7bfb1f6658 in PyDict_SetItemString (v=0x7f7bfb12e280, key=key
entry=0x7f7bfb2db225 "last_traceback", item=0x7f7bfafdf4d0) at Objects/dictobject.c:2439
#24 0x00007f7bfb2938f1 in PySys_SetObject (name=name
entry=0x7f7bfb2db225 "last_traceback", v=<optimized out>) at Python/sysmodule.c:83
#25 0x00007f7bfb28c3de in PyErr_PrintEx (set_sys_last_vars=set_sys_last_vars
entry=1) at Python/pythonrun.c:1173
#26 0x00007f7bfb28c5ca in PyErr_Print () at Python/pythonrun.c:1064
#27 0x00007f7bfb28c7ee in call_sys_exitfunc () at Python/pythonrun.c:1755
#28 Py_Finalize () at Python/pythonrun.c:423
#29 0x00007f7bfb2a2b6c in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:665
#30 0x000000385a61ed20 in __libc_start_main () from /lib64/libc.so.6
#31 0x0000000000400651 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f7bfa514de3 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#6  0x00007f7bfa86898b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#7  0x00007f7bfa866cfc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#8  0x00007f7bfa87e778 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#9  0x00007f7bfa87ebe7 in TFile::~TFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#10 0x00007f7bfa87eef9 in TFile::~TFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libRIO.so
#11 0x00007f7bfa5c04c1 in TClass::Destructor(void*, bool) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_8/external/slc6_amd64_gcc630/lib/libCore.so
#12 0x00007f7bfaee8847 in PyROOT::op_dealloc_nofree(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#13 0x00007f7bfaee88b9 in PyROOT::(anonymous namespace)::op_dealloc(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.08-elfike/lib/libPyROOT.so
#14 0x00007f7bfb213382 in subtype_dealloc (self=0x7f7bf10e7fb0) at Objects/typeobject.c:1030
#15 0x00007f7bfb1dc0b9 in frame_dealloc (f=0x686f960) at Objects/frameobject.c:460
#16 0x00007f7bfb294feb in tb_dealloc (tb=0x7f7beff72c68) at Python/traceback.c:28
#17 0x00007f7bfb294ffb in tb_dealloc (tb=0x7f7beff72cf8) at Python/traceback.c:27
#18 0x00007f7bfb294ffb in tb_dealloc (tb=0x7f7beff72830) at Python/traceback.c:27
#19 0x00007f7bfb1f35e7 in insertdict_by_entry (value=0x7f7bfafdf4d0, ep=0x176d2a0, hash=5897959712516987849, key=0x7f7bfb0109d0, mp=0x7f7bfb12e280) at Objects/dictobject.c:519
#20 insertdict (mp=0x7f7bfb12e280, key=0x7f7bfb0109d0, hash=5897959712516987849, value=0x7f7bfafdf4d0) at Objects/dictobject.c:556
#21 0x00007f7bfb1f4fc7 in dict_set_item_by_hash_or_entry (ep=0x0, value=0x7f7bfafdf4d0, hash=<optimized out>, key=<optimized out>, op=0x7f7bfb12e280) at Objects/dictobject.c:765
#22 PyDict_SetItem (op=0x7f7bfb12e280, key=<optimized out>, value=0x7f7bfafdf4d0) at Objects/dictobject.c:818
#23 0x00007f7bfb1f6658 in PyDict_SetItemString (v=0x7f7bfb12e280, key=key
entry=0x7f7bfb2db225 "last_traceback", item=0x7f7bfafdf4d0) at Objects/dictobject.c:2439
#24 0x00007f7bfb2938f1 in PySys_SetObject (name=name
entry=0x7f7bfb2db225 "last_traceback", v=<optimized out>) at Python/sysmodule.c:83
#25 0x00007f7bfb28c3de in PyErr_PrintEx (set_sys_last_vars=set_sys_last_vars
entry=1) at Python/pythonrun.c:1173
#26 0x00007f7bfb28c5ca in PyErr_Print () at Python/pythonrun.c:1064
#27 0x00007f7bfb28c7ee in call_sys_exitfunc () at Python/pythonrun.c:1755
#28 Py_Finalize () at Python/pythonrun.c:423
#29 0x00007f7bfb2a2b6c in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:665
#30 0x000000385a61ed20 in __libc_start_main () from /lib64/libc.so.6
#31 0x0000000000400651 in _start ()
===========================================================


Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
./test/runAnalysis.sh: line 66: 2237669 Segmentation fault      (core dumped) ./Utilities/scripts/makeFakeRates.py -s ${looselepsfile} -l $lumi -o $frfile
Error in <TFile::TFile>: file data/fakeRate18Apr2017-3LooseLeptons-MediumMuons.root does not exist
[?1034hTraceback (most recent call last):
  File "ScaleFactors/setupScaleFactors.py", line 134, in <module>
    eCBMedFakeRateZjets.Set2DHist(fakeRateFile.Get('DataEWKCorrected/ratio2D_allE'), 0, 0, ROOT.ScaleFactor.AsInHist)
ReferenceError: attempt to access a null-pointer
SysError in <TFile::TFile>: file /afs/cern.ch/work/s/strembat/WZ/dataOutput/HistFiles/VBSselection_Tight-02Aug2018.root can not be opened (No such file or directory)
[?1034hTraceback (most recent call last):
  File "./Utilities/scripts/makeHistFile.py", line 67, in <module>
    mCBTightFakeRate.SetName("fakeRate_allMu")
AttributeError: 'TObject' object has no attribute 'SetName'
ERROR: /afs/cern.ch/work/s/strembat/WZ/dataOutput/HistFiles/VBSselection_Tight-02Aug2018.root was not produced!
